<a href="https://colab.research.google.com/github/Yashavanth547/Yash/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np
 a = [1,2,3,4]
 sum = np.sum(a)
 print("Sum of array elements is",sum)
 min = np.min(a)
 print("Minimum of array elements is",min)
 max = np.max(a)
 print("Maximum of array elements is",max)
 mean = np.mean(a)
 print("Mean of array elements is",mean)
 med = np.median(a)
 print("Median of array elements is",med)
 cor = np.corrcoef(a)
 print("Correaltion coefficiant of array elements is",cor)
 std = np.std(a)
 print("standard deviation of array elements is",std)

Sum of array elements is 10
Minimum of array elements is 1
Maximum of array elements is 4
Mean of array elements is 2.5
Median of array elements is 2.5
Correaltion coefficiant of array elements is 1.0
standard deviation of array elements is 1.118033988749895


In [3]:
mat = [[1,2,3,4],[3,5,6,8],[8,9,3,4]]
sum = np.sum(mat)
print("Sum of matrix elements is",sum)
min = np.min(mat)
print("Minimum of the matrix:",min)
max = np.max(mat)
print("Maximum of the matrix:",max)
mean = np.mean(mat)
print("Mean of the matrix:",mean)
med = np.median(a)
print("Median of the matrix:",med)
cor = np.corrcoef(mat)
print("Correaltion coefficiants of the matrix elements:\n",cor)
std = np.std(mat)
print("standard deviation of array elements is",std)

Sum of matrix elements is 56
Minimum of the matrix: 1
Maximum of the matrix: 9
Mean of the matrix: 4.666666666666667
Median of the matrix: 2.5
Correaltion coefficiants of the matrix elements:
 [[ 1.          0.99227788 -0.78935222]
 [ 0.99227788  1.         -0.70710678]
 [-0.78935222 -0.70710678  1.        ]]
standard deviation of array elements is 2.4608038433722337


In [4]:
 mat = np.array([[1,7,3,4],[3,5,6,8],[10,9,3,4]])
 print(mat)
 sum = np.sum(mat, axis=1)
 print("Sum of array elements row-wise",sum)
 sum = np.sum(mat, axis=0)
 print("Sum of array elements column-wise",sum)
 min = np.min(mat, axis=1)
 print("Row-wise minimum of the matrix:",min)
 max = np.max(mat,axis=0)
 print("Column-wise maximum of the matrix:",max)

[[ 1  7  3  4]
 [ 3  5  6  8]
 [10  9  3  4]]
Sum of array elements row-wise [15 22 26]
Sum of array elements column-wise [14 21 12 16]
Row-wise minimum of the matrix: [1 3 3]
Column-wise maximum of the matrix: [10  9  6  8]


In [5]:
 def sum(a,b):
    return a+b

sum(4,5)

9

In [8]:
def cube(x):
    return x*x*x
cube(4)

64

In [9]:
lambda_cube = lambda y: y*y*y
lambda_cube(5)

125

In [10]:
sum = lambda a,b:a+b
sum(4,5)

9

In [11]:
add = lambda num: num + 4
print( add(6) )

10


In [12]:
 def greater(a,b):
    if a>b:
        return a
    else:
        return b

greater(4,5)

5

In [13]:
 Max = lambda a, b : a if(a > b) else b

Max(4,5)

5

In [16]:
my_list= [5,7,2,8,6]
my_list_squared = []
for i in my_list:
    i_squared = i**2
    my_list_squared.append(i_squared)
my_list_squared

[25, 49, 4, 64, 36]

In [17]:
my_list_squared = [i**2 for i in my_list]
my_list_squared

[25, 49, 4, 64, 36]

In [18]:
my_list_squared = list(map(lambda i: i**2, my_list))
my_list_squared

[25, 49, 4, 64, 36]